### ISSUE TITLE
Install DART

### ISSUE THREAD

**Issue by 0p4ain** [lmco/dart#1]
you can show me any way to install dart on windows 7, beacause i have some errors and i don't know how to overcome ? video demo, nice to have ! thanks so much

**Comment by danmcgowan** [comment]
Thanks for the question! As soon as I get a chance I'll try to post a video of the Win7 installation process. Give me a few days.

**Comment by danmcgowan** [comment]
@0p4ain Thanks for your patience! In making the video for this we caught a minor regression and fixed it in 968b554. 

I think you'll have better luck if you give it another shot with the latest code. Here's a video of the general installation process if you have any other questions: https://youtu.be/CbumTtluL6k
