### ISSUE TITLE
Docker - Alpine Linux must be down graded

### ISSUE THREAD

**Issue by stormworm29** [lmco/dart#16]
For more information about this specific issue kindly check https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.12.0#python2_no_longer_provides_python_and_python-devel

The latest corresponds to 3.12.0 version of Alpine which does not support all the python libraries.

Downgrading the version to 3.11.0 worked for me.

Have raised a pull request to fix the issue https://github.com/lmco/dart/pull/15

Kudos to the Team, amazing software :)

**Comment by cdstelly** [comment]
Agreed - Dockerfile should be pinned to Alpine 3.11

**Comment by Montana** [comment]
Does using a higher version of Alpine still break this? I know the current `Dockerfile` I've attached works, but can it be a different version at this point?

```Dockerfile
FROM alpine:3.11
LABEL maintainer Lockheed Martin Red Team
```

**Comment by stormworm29** [comment]
@Montana - Not sure if there is a newer version of Alpine that works. But I would recommend to fix the version with the latest version that worked for you and version can be updated after its manually verified instead of using **latest**. When I took the code from the main branch and executed, it broke while executing it. I see that one another person has faced this too.

**Comment by Montana** [comment]
I appreciate it @stormworm29.

**Comment by Montana** [comment]
@stormworm29, I will try and work on a fix for this and make a pull request.
