### ISSUE TITLE
[Lockheed Martin: Dart] Dockerfile using `Alpine 3.12.0`

### ISSUE THREAD

**Issue by Montana** [lmco/dart#20]
You must `apk del python` and add `python3` or `python2` for the upgrade to work correctly, as a stale `python` in `/etc/apk/world` will prevent things from upgrading correctly, `abuild-meson` is a small wrapper shellscript that wraps meson (directly inspired by Arch Linux's `arch-meson` and Void Linux's `build_style=meson`), calling it with the correct options for packaging in Alpine Linux. `APKBUILDs` should switch to using it to guarantee all `APKBUILDs` that use meson have the same set of options.

This is the same with OpenRC configuring kernel parameters is done by having configuration files in specific locations like `/etc/sysctl.conf` and files ending with `.conf` in certain directories like /`etc/sysctl.d`. Before `3.12.0` the ordering had no logical explanation and surprised users that expected a hierarchy. With this Lockheed Martin repository, nothing is different.

Starting with 3.12.0 the ordering is as follows:

```bash
/lib/sysctl.d/*.conf
/usr/lib/sysctl.d/*.conf
/run/sysctl.d/*.conf
/etc/sysctl.conf
/etc/sysctl.d/*.conf
```

`/lib/sysctl.d` and `/usr/lib/sysctl.d` are to be used by the distribution and packages. Alpine Linux installs its default configuration file in `/lib/sysctl.d/00-alpine.conf`. Software installed via package manager will install to either of those places.

`/run/sysctl.d` holds configuration that is created at run-time by daemons/services or at very early-boot. Neither the distribution nor the packaged software will install configuration to it, primarily because `/run` is in temporary memory. Configuration in this location that matches names the locations used by the distribution and packages will cause the latter not to be read and applied by the `sysctl service`.

Thank you, 
Montana Mendy

**Comment by Northskool** [comment]
```bash
/etc/sysctl.conf
/etc/sysctl.d/*.conf
```

seemed to work for me @Montana

**Comment by Mixtaped** [comment]
Thank you @Montana! The wrapper worked.

**Comment by Montana** [comment]
Hi @Mixtaped,

Yes you can, here's a screenshot of me running `apk add mysql`: 

<img width="657" alt="Screenshot 2022-11-07 at 10 56 48 PM" src="https://user-images.githubusercontent.com/20936398/200495673-e69863fe-6f3c-4bf9-999b-9e03d5244428.png">

This is in Docker Desktop, I have a Docker Pro account.

**Comment by Montana** [comment]
Closing this issue.
